# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(619, 434)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox1 = QtWidgets.QComboBox(Dialog)
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.gridLayout.addWidget(self.comboBox1, 1, 1, 1, 1)
        self.label5 = QtWidgets.QLabel(Dialog)
        self.label5.setObjectName("label5")
        self.gridLayout.addWidget(self.label5, 3, 0, 1, 1)
        self.comboBox2 = QtWidgets.QComboBox(Dialog)
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.gridLayout.addWidget(self.comboBox2, 2, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.spinBox2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox2.setMaximum(10000)
        self.spinBox2.setObjectName("spinBox2")
        self.gridLayout.addWidget(self.spinBox2, 4, 1, 1, 1)
        self.spinBox1 = QtWidgets.QSpinBox(Dialog)
        self.spinBox1.setMaximum(10000)
        self.spinBox1.setObjectName("spinBox1")
        self.gridLayout.addWidget(self.spinBox1, 3, 1, 1, 1)
        self.label6 = QtWidgets.QLabel(Dialog)
        self.label6.setObjectName("label6")
        self.gridLayout.addWidget(self.label6, 4, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 1, 0, 1, 1)
        self.label4 = QtWidgets.QLabel(Dialog)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 5, 1, 1, 1)
        self.label3 = QtWidgets.QLabel(Dialog)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox1.setItemText(0, _translate("Dialog", "светлая"))
        self.comboBox1.setItemText(1, _translate("Dialog", "средняя"))
        self.comboBox1.setItemText(2, _translate("Dialog", "тёмная"))
        self.comboBox1.setItemText(3, _translate("Dialog", "высшая"))
        self.label5.setText(_translate("Dialog", "Цена"))
        self.comboBox2.setItemText(0, _translate("Dialog", "молотый"))
        self.comboBox2.setItemText(1, _translate("Dialog", "в зёрнах"))
        self.label1.setText(_translate("Dialog", "Название"))
        self.label6.setText(_translate("Dialog", "Объём(мл)"))
        self.label2.setText(_translate("Dialog", "Степень обжарки"))
        self.label4.setText(_translate("Dialog", "Описание"))
        self.label3.setText(_translate("Dialog", "Молотый/В зёрнах"))
        self.pushButton.setText(_translate("Dialog", "Добавить"))
